<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Company>Assimilation Software</Company>
    <Product>TodoSort</Product>
    <Copyright>Copyright © Assimilation Software 2026</Copyright>
    <Version>1.10.1.0</Version>
    <FileVersion>1.10.1.0</FileVersion>
    <InformationalVersion>1.10.1.0</InformationalVersion>
    <PackageVersion>1.10.1.0</PackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Maroon, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Library\Maroon.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
</Project>