<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <InformationalVersion>1.7.4.4</InformationalVersion>
    <PackageVersion>1.7.4.4</PackageVersion>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>Core</AssemblyTitle>
    <Company>Assimilation Software</Company>
    <Product>TodoSort</Product>
    <Copyright>Copyright © Assimilation Software 2025</Copyright>
    <Version>1.7.4.4</Version>
    <FileVersion>1.7.4.4</FileVersion>
    <RootNamespace>AssimilationSoftware.TodoSort.Core</RootNamespace>
    <AssemblyName>TodoSort.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Maroon">
      <HintPath>..\Library\Maroon.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SharpSerializer" Version="4.0.2" />
    <PackageReference Include="System.IO.Abstractions" Version="22.0.14" />
  </ItemGroup>
</Project>